export interface ClientCategoryGroup {
  id: string;
  categoryTitle: string;
  countBadge: string;
  iconName: string;
  clients: string[];
}

export const clientCategoriesData: ClientCategoryGroup[] = [
  {
    id: "comm-it",
    categoryTitle: "Commercial & IT Parks",
    countBadge: "25 Clients",
    iconName: "Building2",
    clients: [
      "Gahri Tech Park",
      "BSR Tech Park",
      "Divyasree NSL (Orion Campus)",
      "Kapil Towers",
      "Astra Towers",
      "Lanco IT",
      "Rajapushpa Summit",
      "Cybersprings",
      "IVY Infotech",
      "L&T Metro Stations",
      "Purva Summit",
      "Kapil Business Park",
      "I Labs",
      "Sattva Knowledge Park",
      "Tech Mahindra",
      "T Hub",
      "Tech Ridge",
      "Cyber Towers",
      "Aurobindo Galaxy",
      "Kapil Kavuri Hub",
      "Sitel India Pvt Ltd",
      "Iocate",
      "Maxicap",
      "Smart Drive",
      "I Sprout",
    ],
  },
  {
    id: "residential",
    categoryTitle: "Residential Communities",
    countBadge: "28 Clients",
    iconName: "Home",
    clients: [
      "Golf Edge Residences",
      "Aparna Silver Oak",
      "Mahindra Ashvita",
      "Golf View",
      "Ramky Towers",
      "Rajapushpa Imperia",
      "Lanco Hills",
      "Rajapushpa Provincia",
      "Kisaan Villas",
      "Hill Country",
      "Rajapushpa Greendale",
      "Jains Balaji",
      "Kalpataru Residency",
      "Sri Sai Ram Towers",
      "The Kotlantis",
      "My Home Mangala",
      "Rainbow Vistas",
      "North Star Villas",
      "Rajapushpa Regalia",
      "Rajapushpa Atria",
      "Manjeera Diamond Tower",
      "L&T Serene County",
      "Aparna Hill Park Avenues",
      "My Home Avatar",
      "Rajapushpa Eterna",
      "Hill Ridge Villas",
      "Aditya Empress",
      "Prajay Megapolis",
    ],
  },
  {
    id: "malls-retail",
    categoryTitle: "Malls Multiplex & Retail",
    countBadge: "13 Clients",
    iconName: "ShoppingBag",
    clients: [
      "Nexus Mall",
      "Marina Mall",
      "Phoenix Market City",
      "GVK One",
      "Lulu Mall",
      "DSL Mall",
      "L&T Mall - Punjagutta",
      "Rajapushpa Provincia",
      "L&T Mall - Hitech City",
      "L&T Mall - Musarambagh",
      "Max Stores",
      "Time Zone",
      "Life Style",
    ],
  },
  {
    id: "hospitals",
    categoryTitle: "Hospitals & Clinics",
    countBadge: "4 Clients",
    iconName: "Hospital",
    clients: [
      "Rainbow Hospitals",
      "Oliva Clinics",
      "Star Health",
      "Rainbow Vistas",
    ],
  },
  {
    id: "warehouses",
    categoryTitle: "Warehouses & Logistics",
    countBadge: "8 Clients",
    iconName: "Warehouse",
    clients: [
      "Max",
      "Life Style",
      "JSL",
      "Metro",
      "LIM Road",
      "Emirates Logistics",
      "Nippon",
      "ILFO",
    ],
  },
  {
    id: "education",
    categoryTitle: "Educational Institutions",
    countBadge: "11 Clients",
    iconName: "GraduationCap",
    clients: [
      "Institute of Public Enterprise",
      "Institute of Public Enterprise",
      "NICMAR",
      "Nalsar",
      "BRL University",
      "Administrative Staff College of India",
      "Jawaharlal Academy",
      "KL University",
      "Delhi Public School",
      "Mahindra and Mahindra University",
      "Analog IAS Academy",
    ],
  },
  {
    id: "manufacturing",
    categoryTitle: "Manufacturing & Pharma",
    countBadge: "11 Clients",
    iconName: "Factory",
    clients: [
      "Vidur Pharma",
      "Drivar Pharma",
      "MSN Pharma",
      "Renew Power Projects",
      "Astra Microwave Products",
      "USilicon Ltd",
      "BHM Ispat Ltd",
      "VRKP Steels Ltd",
      "Pokarna Ltd",
      "MSPL Ltd",
      "RMIL Ltd",
    ],
  },
];
